title: Kim Se-yeon
author: Kim Se-yeon
email: tpdussla93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kim Se-yeon's github pages

# # social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima